version: "3.8"

services:
  grpc-server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

    
  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVER_ADDR: grpc:8080

      